import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
import FooterSection from "@/components/Footer/footer-section";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Black Pixel - Architectural Visualization",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-primary w-screen h-screen ${inter.className}`}>
        <Navbar />
        <main>{children}</main>
        <FooterSection/>
      </body>
    </html>
  );
}
